extends:
  template: ../azure-pipeline-template.yml
  parameters:
    baseMSPath: "$(Build.SourcesDirectory)/appointments/**/*.csproj"
    dockerfilePath: "$(Build.SourcesDirectory)/appointments/Dockerfile"
    testsProjectPath: "$(Build.SourcesDirectory)/appointments/PosTech.Hackathon.Appointments.Tests/*.csproj"
    unitTestFilter: "--filter FullyQualifiedName~PosTech.Hackathon.Appointments.Tests.Unit"

trigger:
  branches:
    include:
      - "main"
      - "development"
  paths:
    exclude:
      - "users/*"
