extends:
  template: ../azure-pipelines-template.yml
  parameters:
    baseMSPath: "$(Build.SourcesDirectory)/users/**/*.csproj"
    dockerfilePath: "$(Build.SourcesDirectory)/users/Dockerfile"
    testsProjectPath: "$(Build.SourcesDirectory)/users/PosTech.Hackathon.Users.Tests/*.csproj"
    unitTestFilter: "--filter FullyQualifiedName~PosTech.Hackathon.Users.Tests.Unit"

trigger:
  branches:
    include:
      - "main"
      - "development"
  paths:
    exclude:
      - "appointments/*"
